import { IRecordData, IRecordData2 } from './Models';

const testData: IRecordData = {
  min5: [
    {
      id: 1,
      userName: 'min5',
      solvedAmount: 15,
      skippedAmount: 3,
    },
    {
      id: 2,
      userName: 'Jane',
      solvedAmount: 22,
      skippedAmount: 14,
    },
    {
      id: 3,
      userName: 'Frank',
      solvedAmount: 3,
      skippedAmount: 12,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
    },
  ],
  flags: [
    {
      id: 1,
      userName: 'noflags',
      solvedAmount: 15,
      skippedAmount: 3,
      timeSpent: 645,
    },
    {
      id: 2,
      userName: '234',
      solvedAmount: 22,
      skippedAmount: 14,
      timeSpent: 12252,
    },
    {
      id: 3,
      userName: '345',
      solvedAmount: 3,
      skippedAmount: 12,
      timeSpent: 4332,
    },
    {
      id: 4,
      userName: '431',
      solvedAmount: 3,
      skippedAmount: 2,
      timeSpent: 5000,
    },
  ],
  all: [
    {
      id: 1,
      userName: 'all',
      solvedAmount: 15,
      skippedAmount: 3,
      timeSpent: 645,
    },
    {
      id: 2,
      userName: 'Jane',
      solvedAmount: 22,
      skippedAmount: 14,
      timeSpent: 12252,
    },
    {
      id: 3,
      userName: 'Frank',
      solvedAmount: 3,
      skippedAmount: 12,
      timeSpent: 4332,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      timeSpent: 5000,
    },
  ],
};
const testData2: IRecordData2 = {
  min5: [
    {
      id: 1,
      userName: 'min5',
      solvedAmount: 15,
      skippedAmount: 3,
      field1: 29392392932323,
      field2: 29392392932323,
      field3: 29392392932323,
      field4: 29392392932323,
      field5: 29392392932323,
      field6: 29392392932323,
    },
    {
      id: 2,
      userName: 'Jane',
      solvedAmount: 22,
      skippedAmount: 14,
      field1: 2,
      field2: 2,
      field3: 2,
      field4: 2,
      field5: 2,
      field6: 2,
    },
    {
      id: 3,
      userName: 'Frank',
      solvedAmount: 3,
      skippedAmount: 12,
      field1: 22,
      field2: 22,
      field3: 22,
      field4: 22,
      field5: 22,
      field6: 22,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 54,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 124,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 44,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 44,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
    {
      id: 2222,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      field1: 3,
      field2: 3,
      field3: 3,
      field4: 3,
      field5: 3,
      field6: 3,
    },
  ],
  flags: [
    {
      id: 1,
      userName: 'noflags',
      solvedAmount: 15,
      skippedAmount: 3,
      timeSpent: 645,
    },
    {
      id: 2,
      userName: '234',
      solvedAmount: 22,
      skippedAmount: 14,
      timeSpent: 12252,
    },
    {
      id: 3,
      userName: '345',
      solvedAmount: 3,
      skippedAmount: 12,
      timeSpent: 4332,
    },
    {
      id: 4,
      userName: '431',
      solvedAmount: 3,
      skippedAmount: 2,
      timeSpent: 5000,
    },
  ],
  all: [
    {
      id: 1,
      userName: 'all',
      solvedAmount: 15,
      skippedAmount: 3,
      timeSpent: 645,
    },
    {
      id: 2,
      userName: 'Jane',
      solvedAmount: 22,
      skippedAmount: 14,
      timeSpent: 12252,
    },
    {
      id: 3,
      userName: 'Frank',
      solvedAmount: 3,
      skippedAmount: 12,
      timeSpent: 4332,
    },
    {
      id: 4,
      userName: 'Robert',
      solvedAmount: 3,
      skippedAmount: 2,
      timeSpent: 5000,
    },
  ],
};
export { testData, testData2 };
